### ISSUE TITLE
Piston Heads New Tile Entity

### ISSUE THREAD

**Issue by OnlyBMan** [gentlegiantJGC/Minecraft-World-Converter#1]
Piston heads aren't converted when porting from PC to PE. I did look at your code and made it create tile entities for piston heads too.

`		elif block == 29:
			te = TAG_Compound()
			te["AttachedBlocks"] = TAG_List()
			te["BreakBlocks"] = TAG_List()
			te["id"] = TAG_String(u'PistonArm')
			te["isMovable"] = TAG_Byte(1)
			te["LastProgress"] = TAG_Float()
			te["NewState"] = TAG_Byte()
			te["Progress"] = TAG_Float()
			te["State"] = TAG_Byte()
			te["Sticky"] = TAG_Byte(1)
			te["x"] = TAG_Int(x)
			te["y"] = TAG_Int(y)
			te["z"] = TAG_Int(z)
			chunk.addTileEntity(te)`

`		elif block == 33:
			te = TAG_Compound()
			te["AttachedBlocks"] = TAG_List()
			te["BreakBlocks"] = TAG_List()
			te["id"] = TAG_String(u'PistonArm')
			te["isMovable"] = TAG_Byte(1)
			te["LastProgress"] = TAG_Float()
			te["NewState"] = TAG_Byte()
			te["Progress"] = TAG_Float()
			te["State"] = TAG_Byte()
			te["Sticky"] = TAG_Byte(0)
			te["x"] = TAG_Int(x)
			te["y"] = TAG_Int(y)
			te["z"] = TAG_Int(z)
			chunk.addTileEntity(te)`

And added these to the tileEntityMapping .jsons
Java:  	"minecraft:pistonarmcollision" : "minecraft:piston_head", "minecraft:piston_extension" : "minecraft:piston_extension",
Bedrock: 	"minecraft:pistonarmcollision" : "PistonArm", "minecraft:piston_extension" : "minecraft:movingblock",

Also added those blocks to the needs tile entity thing.

**Comment by OnlyBMan** [comment]
When I meant adding those blocks, I meant the Piston blocks, not the extension block.

**Comment by gentlegiantJGC** [comment]
great thanks. If you want you can make a pull request to change it directly. If not I can look into adding it at some point
